services:
  basic-auth-local-db:
    image: postgres:16.2-alpine
    command: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=basic-auth-db-local
    profiles:
      - local-dev
