logging:
  level:
    dev.langchain4j: INFO

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
      show-details: never

spring:
  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST:no-db-host-set}:${DB_PORT:wrong-db-port-set}/${DB_NAME:no-db-name-set}?reWriteBatchedInserts=true"
    username: "${DB_USERNAME:no-db-username-set}"
    password: "${DB_PASSWORD:no-db-password-set}"
