spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true

basic:
  auth:
    email: "admin@google.com"
    password: "adminpassword"

security:
  jwt:
    secret: "qF0Bb1ODb1mY9+lA2DpZkLeBsfHR6VJ48xI9YCE2+cM="
    expiration: 3600000
